#+TITLE: GFW Doc
#+AUTHOR: Aziz Amerul Faozi

* Pengantar
Dokument ini merupakan penjelasan kerja dan beragam setting configurasi serta 
lokasi log error untuk melakukan perbaikan atau ketika menjalankan aplikasi
yang ditanamkan pada dragonboard ataupun aplikasi yang dijalakan di server.
* Desain
** Client
Untuk Clientnya dibangun dengan menggunakan bahasa C. Menggunakan pthread, curl, sqlite3,
dan libgpsd
*** Run Time
Karena menggunakan dinamic linking maka beberapa runtime harus tersedia di sbc dragonboard.
Tetapi jika anda ingin melakukan development langsung pada device maka berikut  yang harus 
diinstall.

1. GNU build system (autoconf, automake, libtool)
2. Curl
3. pthread
4. sqlite3
*** Install dependency 
#+BEGIN_SRC
sudo apt-get install cmake make unzip
sudo apt-get install uuid-dev
sudo apt-get install libcurl4-openssl-dev 
sudo apt-get install libgps-dev libsqlite3-dev
sudo apt-get install qdsp-start
wget  https://s3.amazonaws.com/json-c_releases/releases/json-c-0.15.tar.gz
tar -zxvf json-c-0.15.tar.gz
cd json-c-0.15
mkdir build &&
cd    build &&

cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_STATIC_LIBS=OFF    \
      .. &&
make && sudo make install
#+END_SRC
*** Clone repository 
#+BEGIN_SRC bash
wget https://github.com/faoziaziz/api-gfw/archive/latest.zip
unzip latest.zip
cd api-gfw-latest/
#+END_SRC
*** Membuat directory installer
sebelum membuat membuild program pertama buatlah directory
#+BEGIN_SRC
sudo mkdir -p /opt/gfw 
sudo chown $USER:$USER /opt/gfw/
#+END_SRC
*** Untuk membuild program
#+BEGIN_SRC
autoreconf -i
./configure --prefix=/opt/gfw/
make 
make install
#+END_SRC
setelah terinstall maka akan ada file 
#+BEGIN_SRC
/opt/gfw/bin/api-gfw-client
#+END_SRC
dengan mengeksekusi file tersebut maka program akan berjalan.
*** Log Error
log error tersedia pada 
#+BEGIN_SRC bash
/opt/gfw/error.log
#+END_SRC
*** Database Device
Jika tidak terdapat koneksi untuk mengirimkan data ke server maka file akan disimpan pada 
database local 
#+BEGIN_SRC bash
/opt/gfw/gfw_data_gps.db
#+END_SRC
*** Konfigurasi Lainnya
Anda juga bisa melakukan setting terhadap nama device, link url API atau  lokasi database local
dengan mengedit file src/conf.h pada code yang di download.
#+BEGIN_SRC c
#ifndef __conf_h
#define __conf_h

/* this debug setting */
#define DEBUG 1
/* url api configuration*/
#define URL_API "http://server.faozi.tech:8083/api-gfw/v1"
  
#define DEVICE "DRAGON001"
#define DATABASE_LOC "/opt/gfw/gfw_data_gps.db"
/* DELAY save to local 10 menit = 600000 milisecond. */
#define DELAY_SAVELOCAL 600000 
/* 
 * DELAY save push to server 1 second to search connection 
 * equals to 1000 milisecond 
 * */
#define DELAY_TO_PUSH 1000

#endif
#+END_SRC

*** Menambahkan script autostart
untuk menambahkan script autostart 
#+BEGIN_SRC BASH
cp autostart.sh /opt/gfw/
#+END_SRC
Jika anda ingin menambahkan autostart pada crontab gunakan perintah crontab -e
#+BEGIN_SRC
crontab -e
#+END_SRC
lalu tambahkan code berikut (terserah, itu adalah baris code)
#+BEGIN_SRC
* * * * * /bin/sh /opt/gfw/autostart.sh
#+END_SRC
** Server
Server menggunakan Spring-boot untuk aplikasi pengolah data dan Redis sebagai data
storagenya. Data yang dikirimkan dari device menuju server menggunakan perantara 
JSON. 
*** Contoh data
Contoh data yang di tampilkan dalam bentuk JSON
#+BEGIN_SRC json
{ 
"id":"27d48518-218a-11eb-9790-3f50feae72b1",
"online":1.6048162822154794E9,
"status":1.0,
"sateliteUsed":15.0,
"mode":3.0,
"time":1.604816282E9,
"altitude":199.31,
"speed":0.0,
"track":96.5,
"pdop":1.3,
"device":"DRAGON001",
"longitude":106.725318833,
"latitude":-6.555990667,
"dateStamp":"Sun Nov  8 06:18:02 2020\n"
}
#+END_SRC
dari data tersebut anda bisa melihat beragam variable berikut penjelasannya
|--------------+-------------------------------------------------------------------|
| variable     | keterangan                                                        |
|--------------+-------------------------------------------------------------------|
| id           | ID merupakan Identitas dari data yang dikirim. Nilai ini dibuat   |
|              | dengan menggunakan UUID.                                          |
| online       | Merupakan variable yang dihasilkan dari status online pada gpsmon |
|              | nilai ini juga memberikan nilai waktu.                            |
| status       | Status gps                                                        |
| sateliteUsed | Merupakan jumlah satelite yang digunakan.                         |
| mode         |                                                                   |
| time         | Merupakan waktu yang digunakan oleh GPS untuk menerima data.      |
|              | Waktu ini dalam format float.                                     |
| altitude     | Nilai ketinggian dari data GPS,                                   |
| speed        | Kecepatan perangkat yang tertangap GPS.                           |
| track        |                                                                   |
| pdop         |                                                                   |
| longitude    | Nilai longitude yang diberikan GPS.                               |
| latitude     | nilai latitude yang diberikan GPS.                                |
| dateStamp    | Merupakan waktu kirim data dari device ke server.                 |
|--------------+-------------------------------------------------------------------|

** Link API pada server 
*** Link API untuk GET semua data 
Untuk mendapatkan data dari seluruh data yang tersimpan pada
server anda bisa melakukan transaksi seperti berikut.
|----------+----------------------------------------------|
| URL      | http://server.faozi.tech:8083/api-gfw/v1/all |
| METHODE  | GET                                          |
| RESPONSE | list Semua Data                              |

*** Link API untuk POST data 
Untuk menambahkan data GPS pada server anda bisa melakukan
transaksi dengan metode seperti berikut
| URL      | http://server.faozi.tech:8083/api-gfw/v1/add |
| METHODE  | POST                                         |
| REQ_BODY | {                                            |
|          | "id":"27d48518-218a-11eb-9790-3f50feae72b1", |
|          | "online":1.6048162822154794E9,               |
|          | "status":1.0,                                |
|          | "sateliteUsed":15.0,                         |
|          | "mode":3.0,                                  |
|          | "time":1.604816282E9,                        |
|          | "altitude":199.31,                           |
|          | "speed":0.0,                                 |
|          | "track":96.5,                                |
|          | "pdop":1.3,                                  |
|          | "device":"DRAGON001",                        |
|          | "longitude":106.725318833,                   |
|          | "latitude":-6.555990667,                     |
|          | "dateStamp":"Sun Nov  8 06:18:02 2020\n"     |
|          | }                                            |
| RESPONSE | Sama seperti REQ_BODY                        |
*** Link untuk Status Server
Untuk keperluan tertentu anda bisa melakukan checking server
dengan melakukan GET pada URL berikut
| URL      | http://server.faozi.tech:8083/api-gfw/v1/status |
| METHODE  | GET                                             |
| RESPONSE | {"kode":1,"status":"OK"}                        |

* Logbook
** Masalah 
*** AutoInsert API
Tanggal kasus : <2020-10-01 Kam 12:31> . 
Deskripsi : Masih ada masalah dengan methode insert id di api. 
Setiap insert data belum bisa autoincremenet id. 

