#+TITLE: GFW


* Pengantar
* Desain

** Format Pesan
*** Contoh data
Contoh data yang di tampilkan dalam bentuk JSON
#+BEGIN_SRC json
{ 
"id":"27d48518-218a-11eb-9790-3f50feae72b1",
"online":1.6048162822154794E9,
"status":1.0,
"sateliteUsed":15.0,
"mode":3.0,
"time":1.604816282E9,
"altitude":199.31,
"speed":0.0,
"track":96.5,
"pdop":1.3,
"device":"DRAGON001",
"longitude":106.725318833,
"latitude":-6.555990667,
"dateStamp":"Sun Nov  8 06:18:02 2020\n"
}
#+END_SRC
dari data tersebut anda bisa melihat beragam variable berikut penjelasannya
| variable     | keterangan                                                        |
|--------------+-------------------------------------------------------------------|
| id           | ID merupakan Identitas dari data yang dikirim. Nilai ini dibuat   |
|              | dengan menggunakan UUID.                                          |
| online       | Merupakan variable yang dihasilkan dari status online pada gpsmon |
|              | nilai ini juga memberikan nilai waktu.                            |
| status       | Status gps                                                        |
| sateliteUsed | Merupakan jumlah satelite yang digunakan.                         |
| mode         |                                                                   |
| time         | Merupakan waktu yang digunakan oleh GPS untuk menerima data.      |
|              | Waktu ini dalam format float.                                     |
| altitude     | Nilai ketinggian dari data GPS,                                   |
| speed        | Kecepatan perangkat yang tertangap GPS.                           |
| track        |                                                                   |
| pdop         |                                                                   |
| longitude    | Nilai longitude yang diberikan GPS.                               |
| latitude     | nilai latitude yang diberikan GPS.                                |
| dateStamp    | Merupakan waktu kirim data dari device ke server.                 |
*** v1
Untuk API versi pertama mengunakan perintah berikut ini
#+BEGIN_SRC txt

{
"id":"5",
"device":"dev112",
"longitude":123.321,
"latitude":321.12,
"dateStamp":"datetimebentukstring"
}

#+END_SRC
Dengan command seperti berikut 
#+BEGIN_SRC bash
curl -X POST http://localhost:8080/api-gfw/v1/add \
-H 'Content-type:application/json' -d \
'{"id":"100", "device": "dev112", "longitude": \
 123.321, "latitude": 321.12, \
"DateStamp": "ngaceng"}'
#+END_SRC

*** v2
Untuk perbaikan di versi pertama dengan tetap mempertahankan 
versi pertama maka format pesan di buat pada v2 adalah sebagai berikut
#+BEGIN_SRC txt
{
"device":"device1234",
"data": {
"position": {
"longitude": [123.321, 123.321, ...]
"latitude": [321.321, 123.321, ...]
"datestamp": ["pos1", "pos2", ...]
}
}
}
#+END_SRC
* Logbook
** Masalah 
*** AutoInsert API
Tanggal kasus : <2020-10-01 Kam 12:31> . 
Deskripsi : Masih ada masalah dengan methode insert id di api. 
Setiap insert data belum bisa autoincremenet id. 

